# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField()),
                ('destination', models.TextField()),
                ('dateOfJourney', models.DateField()),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Car')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Faculty')),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='school',
            new_name='schoolOfWork',
        ),
        migrations.AddField(
            model_name='staff',
            name='NumJourneysOffered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='NumJourneysTakan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='headOfSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Staff'),
        ),
        migrations.AddField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Staff'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='headOfFaculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Staff'),
        ),
    ]
