# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0002_auto_20161024_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='NumJourneysOffered',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='NumJourneysTakan',
        ),
        migrations.AddField(
            model_name='car',
            name='numberOfSeats',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Staff'),
        ),
    ]
