# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0003_auto_20161101_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='journey',
            name='driver',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='facultyName',
            field=models.TextField(max_length=400),
        ),
        migrations.AddField(
            model_name='staffjourney',
            name='JourneyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Journey'),
        ),
        migrations.AddField(
            model_name='staffjourney',
            name='staffId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Staff'),
        ),
    ]
