# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0004_auto_20161117_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facultyName',
            field=models.TextField(max_length=40),
        ),
    ]
