# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0007_auto_20161128_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=models.TextField(choices=[('BELFAST', 'belfast'), ('JORDANSTOWN', 'jordanstown'), ('MAGEE', 'magee'), ('COLERAINE', 'coleraine')]),
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.TextField(choices=[('BELFAST', 'belfast'), ('JORDANSTOWN', 'jordanstown'), ('MAGEE', 'magee'), ('COLERAINE', 'coleraine')]),
        ),
    ]
