# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0010_auto_20170126_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.TextField(),
        ),
    ]
