# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-01 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0011_auto_20170131_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination0ptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='regNum',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='facultyName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='journey',
            name='reason',
            field=models.CharField(default='give a reason', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolName',
            field=models.CharField(max_length=30),
        ),
    ]
