# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0012_auto_20170201_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Destination0ptions'),
        ),
    ]
