# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-02 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0013_auto_20170201_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin0ptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Destination0ptions'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.Origin0ptions'),
        ),
    ]
