# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-08 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0022_auto_20170306_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Origin0ptions',
            new_name='DestinationOptions',
        ),
        migrations.RenameModel(
            old_name='destination0ptions',
            new_name='OriginOptions',
        ),
    ]
