# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0023_auto_20170408_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='cost',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journey',
            name='distance',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.DestinationOptions'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.OriginOptions'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='homeCampus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_pool.OriginOptions'),
        ),
    ]
