# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_pool', '0025_auto_20170410_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journey',
            name='available_seats',
            field=models.SmallIntegerField(default=5),
        ),
    ]
